### PR TITLE
Add keybinding to navigate to the current root project

### PR DESCRIPTION
**Pull request by rvargs**
`Control + A` feels a little awkward to me.
Please feel free to modify or let me know if you want me to change it to a different character or function.

### CODE REVIEW

**Comment by Oloyko** [comment]
Guys, how do you copy to a normal system buffer? For example copy a text
from vim or terminal to Google. I can't figure it out.

Dne čt 3. 10. 2019 22:18 uživatel Ruben V. <notifications@github.com>
napsal:

**Comment by Parth** [comment]
Sick, let me check this out

**Comment by Parth** [comment]
Ah `Ctrl + A` won't work as it's "goto the start of line" on many systems. I don't particularly find `ctrl+h` useful, perhaps we could replace that functionality with this?

**Comment by Parth** [comment]
@Oloyko perhaps let's talk within an issue?

**Pull request merged**
