### PR TITLE
TMUX: Remove input delay after changing panes

### PR DESCRIPTION
**Pull request by ELouisYoung**
Be Fast!

### CODE REVIEW

**Comment by Parth** [comment]
Hi, thanks for this PR, could you elaborate a bit more about what this improvement is. What steps do I need to take to experience the delay this eliminates?

**Comment by codefist** [comment]
it might not be neede anymore.  there used to be a delay for about 500ms after switching panes before regular insert mode was enabled.  I'm trying it without the config now on a new laptop and seeing no difference.

**Comment by codefist** [comment]
for reference https://unix.stackexchange.com/questions/23138/esc-key-causes-a-small-delay-in-terminal-due-to-its-alt-behavior/25638#25638

**Comment by Parth** [comment]
Okay, I'll close then, thank you though!

**Comment by Parth** [comment]
Feel free to reopen if it is needed

**Pull request closed without merging**
